### ISSUE TITLE
What dose this mean

### ISSUE THREAD

**Issue by Marwa-Awad-Ibrahim** [mehmetpower/poco-mehmet#1]
I can not understand this line 

could you please explain it to me :)

alias kdn='kubectl describe no'

**Comment by mehmetpower** [comment]
it helps you use short commands. When you enter kdn, system will use kubectl describe no command directly.
So it makes your life easier for frequently used long commands.

**Comment by Marwa-Awad-Ibrahim** [comment]
thank you Mehmet

**Comment by mehmetpower** [comment]
U're welcome
